### ISSUE TITLE
Form submits automatically when click on OK button in the picker

### ISSUE THREAD

**Issue by NisalG** [tjohnn/vuejs-datetimepicker#4] opened 2017-11-29 06:29 UTC
I used this in a Laravel + Vue.js application and DateTime picker appears properly.
But when I click on the OK button which appears in the picker, the form get submitted automatically. I'm not sure what I'm doing wrong. I have integrated according to the guide lines.
I also tried with both value accepting ways in the documentation.

```
Laravel 5.5
Vue.js "^2.1.10"
vuejs-datetimepicker: "^1.0.3"
Browser: Chrome & Firefox
```

**Comment by tjohnn** [comment] 2017-11-29 06:53
Hi NisalG,
Please try the latest version that I just committed and let me know if the issue is fixed.

**Comment by NisalG** [comment] 2017-11-29 07:14
@tjohnn 
Thank you for the quick response. Now it has been fixed. But when I submit the form, the bounded attribute's value is empty. 
I used `v-model="obj.start_datetime"`

**Comment by tjohnn** [comment] 2017-11-29 09:16
@NisalG 
I can't replicate the error here, I am simply binding the value the value of date to property `dob`  (for example) of the current scope using this code `@update:date-value="val => dob = val"` as the attribute of the <datetime></datetime> tag. See the example in the documentation the way it is being used for more info.

**Comment by NisalG** [comment] 2017-11-29 14:16
I tried as you mentioned but couldn't get it working. Then I used another DateTime picker (https://github.com/ankurk91/vue-bootstrap-datetimepicker) and it worked in my stack(versions) and context. Appreciate your help.

**Closed** 2017-11-29 14:16 UTC
